export const productosDestacados = [
  {
    id: 1,
    nombre: "Kit Americana",
    descripcionCorta: "Kit completo para instalación de canaletas.",
    descripcion: "Incluye todos los accesorios necesarios para la instalación de canaletas en techos, brindando una solución duradera y resistente al agua.",
    imagen: "/assets/productos/kit-americana.webp",
  },
  {
    id: 2,
    nombre: "Membrana asfáltica",
    descripcionCorta: "Lámina impermeabilizante para techos y paredes.",
    descripcion: "Membrana asfáltica ideal para proteger superficies de la humedad y filtraciones, ofreciendo aislamiento térmico y acústico.",
    imagen: "/assets/productos/membrana-plastica.png",
  },
  {
    id: 3,
    nombre: "Policarbonato",
    descripcionCorta: "Láminas translúcidas resistentes y flexibles.",
    descripcion: "Material liviano y de alta resistencia a impactos, ideal para techos y cerramientos translúcidos con protección UV.",
    imagen: "/assets/productos/policarbonato.webp",
  },
  {
    id: 4,
    nombre: "Chapa T101",
    descripcionCorta: "Chapa trapezoidal galvanizada para estructuras.",
    descripcion: "Chapa estructural utilizada en techos y cerramientos industriales y residenciales, resistente a la corrosión y de fácil instalación.",
    imagen: "/assets/productos/chapa-t101.jpeg",
  },
  {
    id: 5,
    nombre: "Chapa Acanalada",
    descripcionCorta: "Chapa liviana y resistente para techos.",
    descripcion: "Fabricada en acero galvanizado, es ideal para cubiertas de viviendas, galpones y otras construcciones livianas.",
    imagen: "/assets/productos/chapa-acanalada.webp",
  },
  {
    id: 6,
    nombre: "Durlock",
    descripcionCorta: "Placas de yeso para divisiones y cielorrasos.",
    descripcion: "Sistema constructivo en seco para la realización de paredes, cielorrasos y revestimientos interiores, ofreciendo aislamiento acústico y térmico.",
    imagen: "/assets/productos/durlock.png",
  },
  {
    id: 7,
    nombre: "Sellador",
    descripcionCorta: "Compuesto para sellado de juntas y grietas.",
    descripcion: "Sellador de alta adherencia para grietas y juntas en distintas superficies, disponible en varios colores.",
    color: ["Negro", "Gris", "Blanco", "Incoloro"],
    imagen: "/assets/productos/durlock.png",
  },
  {
    id: 8,
    nombre: "Babeta",
    descripcionCorta: "Perfiles metálicos para terminaciones en techos.",
    descripcion: "Elemento de terminación en cubiertas de chapa, evita filtraciones y mejora la estética del techo.",
    imagen: "/assets/productos/durlock.png",
  },
  {
    id: 9,
    nombre: "Caño redondo",
    descripcionCorta: "Tubo estructural de acero redondo.",
    descripcion: "Ideal para estructuras metálicas, barandas, soportes y múltiples aplicaciones industriales y arquitectónicas.",
    imagen: "/assets/productos/durlock.png",
  },
  {
    id: 10,
    nombre: "Caño rectangular",
    descripcionCorta: "Tubo estructural de acero rectangular.",
    descripcion: "Utilizado en estructuras de soporte, cerramientos y diversas aplicaciones de construcción metálica.",
    imagen: "/assets/productos/durlock.png",
  },
  {
    id: 11,
    nombre: "Sombreros",
    descripcionCorta: "Terminación metálica para chimeneas y ventilaciones.",
    descripcion: "Accesorio para la protección de ductos de ventilación y chimeneas, evitando la entrada de agua y objetos externos.",
    imagen: "/assets/productos/durlock.png",
  },
];

export const canaletas = [
  {
    id: 12,
    nombre: "Americana",
    nombreCarrito: "Canaleta Americana",
    descripcionCorta: "Canaleta tipo Americana por metro.",
    descripcion: "Diseñada para la conducción de agua de lluvia en techos, con alta resistencia a la intemperie y fácil instalación.",
    imagen: "/assets/productos/canaletas.jpg",
  },
  {
    id: 13,
    nombre: "Media Caña",
    nombreCarrito: "Canaleta Media Caña",
    descripcionCorta: "Canaleta semicircular para drenaje de agua.",
    descripcion: "Canaleta en forma de media caña utilizada para la evacuación de agua en techos y cubiertas.",
    imagen: "/assets/productos/canaletas.jpg",
  },
  {
    id: 14,
    nombre: "7-15-10",
    nombreCarrito: "Canaleta 7-15-10",
    descripcionCorta: "Canaleta metálica para sistemas de drenaje.",
    descripcion: "Elemento fundamental en techos y estructuras para dirigir el flujo de agua pluvial de manera eficiente.",
    imagen: "/assets/productos/canaletas.jpg",
  },
  {
    id: 15,
    nombre: "Banda Peine",
    nombreCarrito: "Canaleta Banda Peine",
    descripcionCorta: "Accesorio metálico para canaletas.",
    descripcion: "Complemento diseñado para mejorar la eficiencia del drenaje en sistemas de canaletas.",
    imagen: "/assets/productos/canaletas.jpg",
  },
  {
    id: 16,
    nombre: "Interna P/Amurar",
    nombreCarrito: "Canaleta Interna Para Amurar",
    descripcionCorta: "Canaleta interna para instalación fija.",
    descripcion: "Canaleta reforzada para instalación en muros, permitiendo una recolección de agua eficaz.",
    imagen: "/assets/productos/canaletas.jpg",
  },
];
